allowBuilds:
  '@google/genai': false
  better-sqlite3: true
  esbuild: true
  node-llama-cpp: false
  node-pty: true
  protobufjs: false
  tree-sitter-go: false
  tree-sitter-javascript: false
  tree-sitter-python: false
  tree-sitter-rust: false
  tree-sitter-typescript: false
